### ISSUE TITLE
Openmage 20.0.6

### ISSUE THREAD

**Issue by loopCM** [customgento/CustomGento_ProductBadges#2]
Openmage 20.0.6 can not show the lable.

**Comment by ceckoslab** [comment]
Hello @loopCM 

Could you share more information about the needed steps in order to reproduce the issue you are experiencing?

A screenshot would be really appreciated :)

Have a nice day!

**Comment by loopCM** [comment]
Thank you very much for replying to my issue.
magento version： Openmage 20.0.6
1、I upload the app js skin file
2、clean the cache and reindexer 
3、enable the ProductBadges
4、create a new label
5、reindexer
![image](https://user-images.githubusercontent.com/1188048/106479060-d98ab780-64e4-11eb-9ed4-b7b15a80af5e.png)
![image](https://user-images.githubusercontent.com/1188048/106479139-ef987800-64e4-11eb-9881-6c97ef0a9f09.png)

Thank you. 
Have a nice day!

**Comment by loopCM** [comment]
Sorry，I have not use Installation Instructions.
